language: node_js
node_js: 
  - "9"

branches:
  only:
    - master
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
#       - google-chrome-beta

before_install:
  # - export CHROME_BIN=chromium-browser
  # - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script :
  - npm run lint
  # - ng test --single-run
  # - npm run e2e
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email :
    on_failure: tonmanna@gmail.com
    on_success: tonmanna@gmail.com